Repository ZigRazor/PyStateMachine, pull requests merged in 2021-10, with the labels that each got.

#34 Update README.md
  README.md
Labels: documentation, hacktoberfest

#32 Added Docstrings
  src/Action.py
  src/Actions.py
  src/Condition.py
  src/Conditions.py
  src/Event.py
  src/State.py
  tests/testBaseStateMachine.py
Labels: documentation, enhancement, hacktoberfest

#36 Added Docstrings to Functions
  src/Action.py
  src/Actions.py
  src/Condition.py
  src/Conditions.py
  src/Event.py
  src/ReadStateMachine.py
  src/State.py
  src/StateMachine.py
  tests/testBaseStateMachine.py
Labels: documentation, hacktoberfest

#41 Added space after # in ReadStateMachine.py
  src/ReadStateMachine.py
Labels: documentation, style, hacktoberfest

#42 Fixing overly long lines
  setup.py
  src/Event.py
  src/ReadStateMachine.py
  src/StateMachine.py
Labels: style, hacktoberfest
